# config.yaml

# directory where images are stored.
image_storage: '/Users/pburnham/Downloads/HCR_testing/'
segChannel: '1DAPI'
# list channels in your images
channelsOfIntestest: ['1CY5','1CY3','1YFP','2CY5','2CY3','2YFP']

# cellpose parameters
segment:
  flowThreshold: 0.6
  cellProbabilityThreshold: -3.5
  nuclearDiameter: 0.0
  GPU: False

# this will dictate how much of your mask is driven by voronoi or disk
cast:
  dilation: 9
